[package]
name = "struck"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
fastrand = "2.3.0"
hound = "3.5.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
